// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	cart "ecommerce/features/cart"

	mock "github.com/stretchr/testify/mock"
)

// CartData is an autogenerated mock type for the CartData type
type CartData struct {
	mock.Mock
}

// Add provides a mock function with given fields: idUser, idProduct
func (_m *CartData) Add(idUser uint, idProduct uint) error {
	ret := _m.Called(idUser, idProduct)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(idUser, idProduct)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: idUser, idCart
func (_m *CartData) Delete(idUser uint, idCart uint) error {
	ret := _m.Called(idUser, idCart)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(idUser, idCart)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByIdC provides a mock function with given fields: idUser, idCart
func (_m *CartData) GetByIdC(idUser uint, idCart uint) (cart.CoreCart, error) {
	ret := _m.Called(idUser, idCart)

	var r0 cart.CoreCart
	if rf, ok := ret.Get(0).(func(uint, uint) cart.CoreCart); ok {
		r0 = rf(idUser, idCart)
	} else {
		r0 = ret.Get(0).(cart.CoreCart)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(idUser, idCart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIdU provides a mock function with given fields: idUser
func (_m *CartData) GetByIdU(idUser uint) ([]cart.CoreCart, error) {
	ret := _m.Called(idUser)

	var r0 []cart.CoreCart
	if rf, ok := ret.Get(0).(func(uint) []cart.CoreCart); ok {
		r0 = rf(idUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cart.CoreCart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(idUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: idUser, idCart, updatedData
func (_m *CartData) Update(idUser uint, idCart uint, updatedData cart.CoreCart) (cart.CoreCart, error) {
	ret := _m.Called(idUser, idCart, updatedData)

	var r0 cart.CoreCart
	if rf, ok := ret.Get(0).(func(uint, uint, cart.CoreCart) cart.CoreCart); ok {
		r0 = rf(idUser, idCart, updatedData)
	} else {
		r0 = ret.Get(0).(cart.CoreCart)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, uint, cart.CoreCart) error); ok {
		r1 = rf(idUser, idCart, updatedData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCartData interface {
	mock.TestingT
	Cleanup(func())
}

// NewCartData creates a new instance of CartData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCartData(t mockConstructorTestingTNewCartData) *CartData {
	mock := &CartData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
