// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	helper "ecommerce/helper"

	mock "github.com/stretchr/testify/mock"
)

// mediaUpload is an autogenerated mock type for the mediaUpload type
type mediaUpload struct {
	mock.Mock
}

// AvatarUpload provides a mock function with given fields: avatar
func (_m *mediaUpload) AvatarUpload(avatar helper.Avatar) (string, error) {
	ret := _m.Called(avatar)

	var r0 string
	if rf, ok := ret.Get(0).(func(helper.Avatar) string); ok {
		r0 = rf(avatar)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(helper.Avatar) error); ok {
		r1 = rf(avatar)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoteUpload provides a mock function with given fields: url
func (_m *mediaUpload) RemoteUpload(url helper.Url) (string, error) {
	ret := _m.Called(url)

	var r0 string
	if rf, ok := ret.Get(0).(func(helper.Url) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(helper.Url) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMediaUpload interface {
	mock.TestingT
	Cleanup(func())
}

// newMediaUpload creates a new instance of mediaUpload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMediaUpload(t mockConstructorTestingTnewMediaUpload) *mediaUpload {
	mock := &mediaUpload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
