// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Transaction_DetailService is an autogenerated mock type for the Transaction_DetailService type
type Transaction_DetailService struct {
	mock.Mock
}

type mockConstructorTestingTNewTransaction_DetailService interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransaction_DetailService creates a new instance of Transaction_DetailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransaction_DetailService(t mockConstructorTestingTNewTransaction_DetailService) *Transaction_DetailService {
	mock := &Transaction_DetailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
