// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	transaction "ecommerce/features/transaction"

	mock "github.com/stretchr/testify/mock"
)

// TrxService is an autogenerated mock type for the TrxService type
type TrxService struct {
	mock.Mock
}

// Add provides a mock function with given fields: token, newTrx
func (_m *TrxService) Add(token interface{}, newTrx transaction.Core) (transaction.Core, error) {
	ret := _m.Called(token, newTrx)

	var r0 transaction.Core
	if rf, ok := ret.Get(0).(func(interface{}, transaction.Core) transaction.Core); ok {
		r0 = rf(token, newTrx)
	} else {
		r0 = ret.Get(0).(transaction.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, transaction.Core) error); ok {
		r1 = rf(token, newTrx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTrxService interface {
	mock.TestingT
	Cleanup(func())
}

// NewTrxService creates a new instance of TrxService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTrxService(t mockConstructorTestingTNewTrxService) *TrxService {
	mock := &TrxService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
